export const PRIVACY_POLICY_HTML = `
    <div class="legal-paragraph">
        ConvertHub v2 is an offline-first desktop application designed with your privacy as a fundamental priority. All file processing and conversions happen entirely on your local machine; your files never leave your computer. There are no user accounts, no analytics tracking, no telemetries, and no advertisements.
    </div>
    
    <h3 class="legal-section-title">What We Collect</h3>
    <div class="legal-paragraph">
        Nothing. ConvertHub v2 does not collect, store, or transmit any personal data, usage statistics, conversion logs, or crash reports. Your activity within the application remains entirely private to your device.
    </div>
    
    <h3 class="legal-section-title">Auto-Updater</h3>
    <div class="legal-paragraph">
        The app includes an auto-updater feature to ensure you have access to the latest improvements and security fixes. When checking for updates, ConvertHub v2 makes a secure HTTPS request to GitHub Releases. During this standard HTTP request, GitHub's servers may log network metadata such as your IP address. This interaction is governed strictly by GitHub's Privacy Statement. If you prefer not to check for updates automatically, you can disable this feature in the app settings.
    </div>
    
    <h3 class="legal-section-title">Third-Party Engines</h3>
    <div class="legal-paragraph">
        ConvertHub v2 bundles pre-compiled binary engines — FFmpeg, LibreOffice, and 7-Zip — to perform local conversions and operations. These engines run strictly on your local machine within your system environment. They do not initiate network connections, transmit telemetry, or send data externally. All output generated by these tools is saved directly to your local disk.
    </div>
    
    <h3 class="legal-section-title">Children's Privacy</h3>
    <div class="legal-paragraph">
        ConvertHub v2 does not target children and does not knowingly collect personal information from anyone, including children under the age of 13.
    </div>
    
    <h3 class="legal-section-title">Changes to This Policy</h3>
    <div class="legal-paragraph">
        We may update this Privacy Policy from time to time. Any changes will be reflected directly in this file within the repository, along with an updated date at the top of the page.
    </div>
`;

export const TERMS_OF_USE_HTML = `
    <div class="legal-paragraph">
        Welcome to ConvertHub v2. Please read these Terms of Use carefully before using the application.
    </div>
    
    <h3 class="legal-section-title">License</h3>
    <div class="legal-paragraph">
        ConvertHub v2 is free open-source software released under the MIT License. You are free to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software. See the LICENSE file in the repository root for full details.
    </div>
    
    <h3 class="legal-section-title">Acceptable Use</h3>
    <div class="legal-paragraph">
        You are solely responsible for ensuring that you have the necessary rights, permissions, and licenses for any files processed using ConvertHub v2. You agree not to use this software to infringe upon copyright or intellectual property rights, circumvent Digital Rights Management (DRM) protections, or process illegal or unlawful content.
    </div>
    
    <h3 class="legal-section-title">No Warranty</h3>
    <div class="legal-paragraph">
        ConvertHub v2 is provided "as is", without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, data integrity, or non-infringement. Output quality and conversion accuracy may vary depending on input formats and underlying tools. Use the software at your own risk.
    </div>
    
    <h3 class="legal-section-title">Liability Limitation</h3>
    <div class="legal-paragraph">
        To the maximum extent permitted by applicable law, the developer (Priyansh Verma) and contributors shall not be liable for any claims, damages, loss of data, file corruption, or other liabilities arising from or connected with your use of or inability to use ConvertHub v2.
    </div>
    
    <h3 class="legal-section-title">Third-Party Engines</h3>
    <div class="legal-paragraph">
        ConvertHub v2 bundles standalone open-source utilities for convenience, including FFmpeg, LibreOffice, and 7-Zip. These binaries remain independent projects governed by their respective open-source licenses. For detailed license information and component source attributions, please refer to THIRD_PARTY_LICENSES.md.
    </div>
    
    <h3 class="legal-section-title">Updates</h3>
    <div class="legal-paragraph">
        The built-in automatic update check is provided for user convenience. The developer is under no obligation to provide ongoing updates, software maintenance, bug fixes, or specific features.
    </div>
`;
